/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData water = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData drugs = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pill_vertical = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData more_1 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData ruler = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData more_2 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData medicine_bottle = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData emergency = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData vaccine = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData oval = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData color_pill = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData circle = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData dose = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData medicine_bottle_1 = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData spray = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData inhaler = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData spoon = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData eye_dropper = const IconData(0xe824, fontFamily: _kFontFam);
}
